import { raleway, roboto } from "@/fonts";
import "./globals.css";

export const metadata = {
  title: "Global Work Home",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${ roboto.variable } antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
